export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const RESTORE_CART = "RESTORE_CART";
export const UPDATE_CART_COUPON = "UPDATE_CART_COUPON";
export const COUPON_ERROR = "COUPON_ERROR";
export const CLEAR_CART = "CLEAR_CART";
