export const PAY_FOR_ORDER = "PAY_FOR_ORDER";
export const ORDER_FAILED = "ORDER_FAILED";
export const ORDER_RESPONSE_CLEAR = "ORDER_RESPONSE_CLEAR";
export const GET_ORDERS = "GET_ORDERS";
export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER";
export const ORDER_START = "ORDER_START";
